name: 'Deploy SonarQube'
on: 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Connexion au cluster kubernetes
      run: |
        mkdir ~/.kube/
        echo -e "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          
    - name: SonarQube Installation
      run: cat ~/.kube/config
