name: 'Deploy SonarQube'
on: 
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Connexion au cluster kubernetes
      run: |
        mkdir ~/.kube/
        echo -e "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          
    - name: SonarQube Installation
      run: |
        ls -la
        pwd
        SONARQUBE_NODE=kubectl get nodes | awk '{print $1}' |  awk 'NR == 2 { print ; exit ;}'
        kubectl taint nodes $SONARQUBE_NODE sonarqube=true:NoSchedule
        kubectl label node $SONARQUBE_NODE sonarqube=true
        helm repo add sonarqube https://SonarSource.github.io/helm-chart-sonarqube
        helm repo update
        kubectl create namespace sonarqube
        helm upgrade --install -n sonarqube sonarqube sonarqube/sonarqube
        helm upgrade -f ./values.yaml --install -n sonarqube sonarqube sonarqube/sonarqube
