name: 'Deploy SonarQube'
on: 
  workflow_dispatch:

env:
  RESOURCE_GROUP_NAME: myResourceGroupA1

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Connexion au cluster kubernetes
      run: |
        mkdir ~/.kube/
        echo -e "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        
    - name: Création de l'infrastructure
      run: |
        az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location westeurope
        az aks create -n myCluster -g ${{ env.RESOURCE_GROUP_NAME }}
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name myCluster
